// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using island_back.Models;

#nullable disable

namespace island_back.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("island_back.Models.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityAssigneeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityAssigneeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivityCreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityCreatorID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityCreatorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivityDoneTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivityDueTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityTargetID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityTargetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityID");

                    b.HasIndex("ActivityTypeID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("island_back.Models.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivityTypeDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("ActivityTypeID");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("island_back.Models.Activity", b =>
                {
                    b.HasOne("island_back.Models.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");
                });
#pragma warning restore 612, 618
        }
    }
}
